config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create]
  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end

  delete 'logout' => 'sessions#destroy'

  root 'home#index'
  
  get 'home/index'
  
  get "/conversation/:id/new" => "conversations#new", as: :new_conversation

  get "/conversation/:conversation_id/messages/:id/view" => "messages#view", as: :view_message

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  has_many :messages
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, uniqueness: true
  validates :name, presence: true

  has_many :conversations
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id session[:user_id]
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def new
    @conversation = Conversation.get(current_user.id, params[:id])
  end

  def create
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all.where.not(id: current_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = Conversation.includes(:recipient).find(params[:conversation_id])
    @message = @conversation.messages.create(message_params)
    @sender = User.find(@message.user_id)
    redirect_to new_conversation_path(check(@conversation))
  end

  def check(conversation)
    if conversation.sender_id == current_user.id 
      conversation.recipient_id
    else
      conversation.sender_id
    end
  end

  def view
    @conversation = Conversation.includes(:recipient).find(params[:conversation_id])
    @message = Message.find(params[:id])
    if @message.update_attributes(read_at: DateTime.now.to_date)
      # redirect_to view_message_path(@conversation.id, @message.id)
    end
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out."
    redirect_to root_path
  end

  def create
    if @user = User.find_by(email: params[:email]) and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, flash: {success: "Logged in."}
    else
      flash.now[:error] = "Invalid email or password"
      render 'new'
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id
      flash[:success] = "Registered successfully."
      redirect_to root_path
    else 
      flash.now[:error] = "Error #{@user.errors.full_messages.to_sentence}"
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def flash_class_name(key)
    case key.to_s
    when 'success'
      "alert-info"
    when 'error'
      "alert-danger"
    else
      "alert-warning"
    end
  end
end

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
    <%= render message, user: current_user %>
  <% end %>

app/views/conversations/new.html.erb
<div class="panel panel-default">
  <div class="panel-body" >
    <div class="messages-list">
      <table class="table">
        <thead class="thead thead-default"> 
          <tr>
            <th>Sender</th>
            <th>Message body</th>
            <th>Read at</th>
          </tr>
        </thead>

        <tbody>
          <% @conversation.messages.order(created_at: 'desc').each do |m| %> 
            <tr>
              <td><%= User.find(m.user_id).email %></td>
              <% if m.read_at.present? %>
                <td><%= m.body %></td>
                <td><%= m.read_at %></td>
              <% else %>
                <td><b><%= m.body %></b></td>
                <td><%= link_to 'View', view_message_path(@conversation.id, m.id) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= form_for [@conversation, @conversation.messages.new] do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_area :body, class: "form-control" %>
      <%= f.submit "Send", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<h2>Users</h2>
  <table class="table">
    <thead class="thead thead-default"> 
      <tr>
        <th>Name</th>
        <th>Email</th>
        <% if session[:user_id] %>
          <th>Chat Please</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %> 
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <% if session[:user_id] %>
            <td><%= link_to 'Chat With Me', new_conversation_path(user.id) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to "Register", new_user_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="<%= root_path %>">Parler</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if current_user %>
      <li class="nav-item">
        Welcome, <%= current_user.name %>
        <%= link_to "Log out", logout_path, class: 'nav-link', method: 'delete' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign in", new_session_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "Sign up", new_user_path, class: 'nav-link' %>
      </li>
    <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <div class="alert alert-info">
        Welcome, <%= current_user.name %>
        <%= link_to "Log out", logout_path, method: 'delete' %>
      </div>
    <% else %>
      <%= link_to "Log in", new_session_path %>
    <% end %>

    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <div class="alert <%= flash_class_name(key) %>">
          <%= value %>
        </div>
      <% end %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<li>
  <div class="row">
      <%= message.body %>
  </div>
</li>

app/views/messages/view.html.erb
<h1><%= @message.body %></h1>

app/views/users/new.html.erb
<h1>Register</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.submit %>
<% end %>